config/routes.rb
Blogapp::Application.routes.draw do

 devise_for :users, :controllers => {
  :omniauth_callbacks => 'users/omniauth_callbacks',
  :sessions => "users/sessions",
  :registrations => "users/registrations",
  :passwords => "users/passwords"
}
resources :users, :only => [:index, :show, :destroy] do 
  resources :follows, only: [:create, :destroy]
  member do
    get :following, :follower, :favorite
  end
end

resources :articles do 
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy] 
end

namespace :admin do
  resources :users, :only => [:index, :show, :destroy] do
    collection do 
      delete :destroy_all_users
    end
  end
  resources :articles, :only => [:index, :show, :destroy] do 
    collection do 
      delete :destroy_all_articles  
    end
  end
end

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, 
  :recoverable, 
  :rememberable, 
  :validatable,
  :trackable,
  :confirmable,
  :registerable,
  :omniauthable,
  :authentication_keys => [:username]

  validates :username, presence: true

  has_many :articles, 
  dependent: :destroy

  has_many :comments, 
  dependent: :destroy

  has_many :favorites, 
  dependent: :destroy

  has_many :follows, 
  dependent: :destroy 

  has_many :reverse_follows, 
  foreign_key: "followed_id",
  class_name:  "Follow",
  dependent: :destroy

  mount_uploader :image, ImageUploader

  def user_image
    user = User.find(self)
    if user.image.blank?
      if user.uid
        uid = user.uid.to_s
        "https://graph.facebook.com/"+uid+"/picture?type=square"
      else
        "http://www.oomoto.or.jp/japanese/_src/sc6732/90l95A883A83C83R8393.jpg"
      end
    else
      user.image_url(:thumb).to_s
    end
  end
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value", { :value => username }]).first
    else
      where(conditions).first
    end
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        username: auth.info.name,
        email: auth.info.email,
        password: Devise.friendly_token[0, 20]
        )
    end
    user
  end 


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]
  def index
    @users = User.all
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to :back
  end

  def destroy_all_user
    User.all.destroy_all
    redirect_to :back
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      token = "CAAWF8XmmjJEBAI2bTSdbm0UWBWcBgFB1DZCCGD6yM4ZAqYfjmyZB7JFyiQGSsFNZBmtw2LWWkz3qmbt7QmgZC8doxMyECRLRb6GpXGdhnXC7HIt9vFPZAB0bsGaKOqFco9HoKYFuSykHRbB6yHQWZC8LtRGOxssIxPywp5rwoGHKUPXLiTw6oYR3JzFzcAWO7fs5UsD4rhLa1OiR5Y3WDxd"
      facebook = Koala::Facebook::API.new(token)
      redirect_to new_user_registration_url
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   # def create
   #   super
   # end

  # GET /resource/edit
   #def edit
    # super
   #end

  # PUT /resource
  # def update
   #  super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #     super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show,:destroy, :following, :followers, :favorite]
	before_filter :authenticate_user!
	before_action :check_admin, only: [:delete_all_users, :delete_all_articles]

	def index
		follows = Follow.where(user_id: current_user.id).pluck(:followed_id) << current_user.id
		@articles = Article.where(user_id: follows).includes(:user,:favorites).sort.reverse
	end
	
	def show
		@user_articles = Article.where(user_id: @user.id).includes(:favorites)
		@follows = Follow.all
	end

	def following
		user_follows = Follow.where(user_id: @user.id).pluck(:followed_id)
		@users = User.includes(:follows,:reverse_follows,:articles).find(user_follows)
	end

	def follower
		followers = Follow.where(followed_id: @user.id).pluck(:user_id)
		@users = User.includes(:follows,:reverse_follows,:articles).find(followers)
	end

	def favorite
		favorites = Favorite.where(user_id: @user.id).pluck(:article_id)
		@articles = Article.find(favorites)
	end

	def destroy
		@user.destroy
		redirect_to :back
	end

	# def destroy_all_users
	# 	@users = User.all
	# 	@users.destroy_all
	# 	redirect_to :back 
	# end

	# def destroy_all_articles
	# 	Article.all.destroy_all
	# 	redirect_to :back
	# end

	private
	def set_user
		@user = User.find(params[:id])
	end

	def check_admin
		unless current_user.admin?
			redirect_to users_path
		end
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin.html.erb
	<div class="main">
		<div class="sidebar">
			<ul>
				<li class="side_box"><%= link_to "記事一覧",admin_articles_users_path %></li>
				<li class="side_box"><%= link_to "ユーザー一覧",admin_users_path %></li>
			</ul>
			<img src="http://i.gzn.jp/img/2011/12/26/shirokuro-social-icons/icon-white-web.png">
		</div>
		<div class="contents">
			<div class="contents-top">
				<h1>ユーザー一覧</h1>
				<span><button class="clear"><%= link_to "ユーザー初期化",delete_all_users_users_path, method: :delete , data: {confirm: "本当に削除しますか？"} %></button></span>
				<div class="contents-bottom">
					<table>
						<tr>
							<th class="th-11">ID</th>
							<th class="th-12">画像</th>
							<th class="th-13">名前</th>
							<th class="th-14">作成時</th>
							<th class="th-15">記事数</th>
							<th class="th-15">フォロー</th>
							<th class="th-15">フォロワー</th>
							<th class="th-16">削除</th>
						</tr>
						<% @users.each do |f| %>
						<tr>
							<td class="th-11"><%= f.id %></td>
							<td class="th-12"><%= image_tag(f.user_image) %></td>
							<td class="th-13"><%= link_to f.username ,user_path(f) %></td>
							<td class="th-14"><%= tokyotime(f.created_at) %></td>
							<td class="th-15"><%= f.articles.size -%></td>
							<td class="th-15"><%= f.follows.size -%></td>
							<td class="th-15"><%= f.reverse_follows.size -%></td>
							<td class="th-16"><%= link_to image_tag("/assets/drop.jpg/"), user_delete_user_path(f), method: :delete , data: {confirm: "本当に削除しますか？"} -%></td>
						</tr>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</body>
	</html>

app/views/users/admin_articles.html.erb
	<div class="main">
		<div class="sidebar">
			<ul>
				<li class="side_box"><%= link_to "記事一覧",admin_articles_users_path %></li>
				<li class="side_box"><%= link_to "ユーザー一覧",admin_users_path %></li>
			</ul>
			<img src="http://i.gzn.jp/img/2011/12/26/shirokuro-social-icons/icon-white-web.png">
		</div>
		<div class="contents">
			<div class="contents-top">
				<h1>記事一覧</h1>
				<span><button class="clear"><%= link_to "記事初期化",delete_all_articles_users_path, method: :delete , data: {confirm: "本当に削除しますか？"} %></button></span>
				<div class="contents-bottom">
					<table>
						<tr>
							<th class="th-1">ID</th>
							<th class="th-2">タイトル</th>
							<th class="th-12">写真</th>
							<th class="th-3">作成者</th>
							<th class="th-4">作成時</th>
							<th class="th-6">ふぁぼ</th>
							<th class="th-6">削除</th>
						</tr>
						<% @articles.each do |f| %>
						<tr>
							<td class="th-1"><%= f.id %></td>
							<td class="th-2"><%= link_to f.title, article_path(f)%></td>
							<td class="th-12"><%= image_tag(f.image_url(:thumb).to_s) %></td>
							<td class="th-3"><%= f.user.username %></td>
							<td class="th-4"><%= tokyotime(f.created_at) %></td>
							<td><%= f.favorites.size %></td>
							<td class="th-6"><%= link_to image_tag("/assets/drop.jpg/"), article_path(f), method: :delete , data: {confirm: "本当に削除しますか？"} -%></td>
						</tr>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</body>
	</html>

app/views/users/all_users.html.erb
<h1>友達を探す</h1><br><br>
<div class="container">
	<table class="table-hover">
		<thead>
			<tr>
				<th>プロフィール</th>
				<th>名前</th>
				<th>フォロー数</th>
				<th>フォロワー数</th>
				<th>記事数</th>
				<th>フォロー外す</th>
			</tr>
		</thead>
		<% @users.each do |f| %>
		<tbody>
			<tr>
				<td><%= image_tag (f.user_image) %></td>
				<td><%= link_to f.username ,user_path(f) %></td>
				<td><%= f.follows.size %></td>
				<td><%= f.reverse_follows.size %></td>
				<td><%= f.articles.size %></td>
				<% if current_user.follows.find_by(followed_id: f) %>
				<td><button class="btn btn-danger"><%= link_to "unfollow", follow_path(current_user.follows.find_by(followed_id: f)) ,method: :delete %></button></td>
				<% else %>
				<td><button class="btn btn-primary"><%= link_to "follow", user_follows_path(f) , method: :post %></button></td>
				<% end %>
			</tr>
		</tbody>
		<% end -%>
	</table>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag "profile" %>
<h1><%= current_user.username %>のタイムライン</h1>
<div id="container">
	<div id="main">
		<% @articles.each do |article| %>
		<div id="contents">
			<div class="title"><%= link_to image_tag(article.user.user_image) ,user_path(article.user_id) %></div>
			<h2 class="title"><%= article.title %></h2>
			<% if article.favorites.find_by(user_id: current_user)  %>
			<h2 class="favorite"><%= link_to "♥",favorite_path(article.favorites.find_by(user_id: current_user)), method: :delete %></h2>
			<% else %>
			<h2 class="favorite"><%= link_to "♡",article_favorites_path(article),method: :post %></h2>
			<% end -%>
			<h3 class="favorite"><%= link_to "show",article_path(article)%></h3>
			<br><br><br><br><br>
			<div class="item" ><%= image_tag article.image_url%></div>
			<div class="article"><%= article.article %></div>
		</div>
		<% end -%>
	</div>
</div>

app/views/users/show.html.erb
<% if current_user.admin? %>
  <%= render 'layouts/admin_profile' %>
<% else %>
  <%= render 'layouts/profile' %>
<% end -%>