config/routes.rb
Blogapp::Application.routes.draw do

 devise_for :users, :controllers => {
  :omniauth_callbacks => 'users/omniauth_callbacks',
  :sessions => "users/sessions",
  :registrations => "users/registrations",
  :passwords => "users/passwords"
}
resources :users, :only => [:index, :show, :destroy] do 
  resources :follows, only: [:create, :destroy]
  member do
    get :following, :follower, :favorite
  end
end

resources :articles do 
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy] 
end

namespace :admin do
  resources :users, :only => [:index, :show, :destroy] do
    collection do 
      delete :destroy_all_users
    end
  end
  resources :articles, :only => [:index, :show, :destroy] do 
    collection do 
      delete :destroy_all_articles  
    end
  end
end

  root 'users#index'

end

app/views/layouts/_admin_article.html.erb
<span class="admin">管理者専用</span>
<div class="container" style="text-align: center">
	<h1><%= @article.title%>　♥</h1>
		<p><%= @article.article%></p>
	<div class="item"><%= image_tag @article.image_url %></div><br><br>
	<div>
 		<h3>comment</h3>
		<% @comments.each do |comment| %>
			<p>
				<%= comment.comment %>
				<% if comment.user_id == current_user.id %>
				<%= link_to "delete", article_comment_path(comment.article_id, comment), method: :delete %>
				<% end -%>
			</p>
		<% end %>
</div>

app/views/layouts/_admin_favorite.html.erb
<%= stylesheet_link_tag 'profile' %>
<span class="admin">管理者専用</span>
<h1><%= @user.username %>のお気に入り</h1><br><br>
<div class="container">
	<table class="table-hover">
		<thead>
			<tr>
				<th>記事名</th>
				<th>写真</th>
				<th>お気に入り数</th>
			</tr>
		</thead>
		<% @articles.each do |f| %>	
		<tbody>
			<tr>
				<td><%= link_to f.title , article_path(f) %></td>
				<td><%= image_tag(f.image_url(:thumb).to_s) %></td>
				<td><%= f.favorites.size%></td>
			</tr>
			<% end -%>
		</tbody>
	</table>
</div>

app/views/layouts/_admin_follow.html.erb
<span class="admin">管理者専用</span>
<h1><%= @user.username %>がフォローしている人</h1>
<br><br>
<div class="container">
	<table class="table-hover">
		<thead>
			<tr>
				<th>プロフィール</th>
				<th>名前</th>
				<th>フォロー数</th>
				<th>フォロワー数</th>
				<th>記事数</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |f| %>
			<tr>
				<td><%= image_tag f.user_image %></td>
				<td><%= link_to f.username ,user_path(f) %></td>
				<td><%= f.follows.size %></td>
				<td><%= f.reverse_follows.size %></td>
				<td><%= f.articles.size %></td>
			</tr>
			<% end -%>
		</tbody>
	</table>
</div>

app/views/layouts/_admin_follower.html.erb
<span class="admin">管理者専用</span>
<h1><%= @user.username %>のフォロワー</h1>
<br><br>
<div class="container">
	<table class="table-hover">
		<thead>
			<tr>
				<th>プロフィール</th>
				<th>名前</th>
				<th>フォロー数</th>
				<th>フォロワー数</th>
				<th>記事数</th>
			</tr>
		</thead>
			<% @users.each do |f| %>		
		<tbody>
			<tr>
				<td><%= image_tag f.user_image %></td>
				<td><%= link_to f.username, user_path(f) %></td>
				<td><%= f.follows.size %></td>
				<td><%= f.reverse_follows.size %></td>
				<td><%= f.articles.size %></td>
			</tr>
		</tbody>
		<% end -%>
	</table>
</div>

app/views/layouts/_admin_navbar.html.erb
  <%= stylesheet_link_tag 'admin' %>
  <div class="header">
    <div class="header-left">管理者画面</div>
    <div class="header-right">
      <ul>
        <li class="selected"><%= link_to "TOP",admin_users_path %></li>
        <li><%= link_to '管理者編集', edit_user_registration_path %></li>
        <li><%= link_to "Out", destroy_user_session_path, :method => :delete%></li>
      </ul>
    </div>
  </div>
  <%= yield %>

app/views/layouts/_admin_profile.html.erb
<%= stylesheet_link_tag 'profile' %>
<span class="admin">管理者専用</span>
<h1><%= @user.username %>のページ</h1><br>
	<div class="container">
		<span>
			<%= link_to @user.follows.size, user_follows_path(@user) %> follows
		</span>
		<span>
			<%= link_to @user.reverse_follows.size,follower_user_follows_path(@user) %> followers
		</span>
		<span>
			<%= link_to @user.username+"のお気に入り",user_favorites_path(@user) %>
		</span>
		<table class="table-hover">
			<thead>
				<tr>
					<th>記事名</th>
					<th>写真</th>
					<th>作成時</th>
					<th>お気に入り数</th>
				</tr>
			</thead>
		  <% @user_articles.each do |article| %>	
				<tbody>
					<tr>
						<td><%= link_to article.title, article_path(article) %></td>
						<td><%= image_tag(article.image_url(:thumb).to_s) %></td>
						<td><%= tokyotime(article.created_at) %></td>
						<td><%= article.favorites.count%></td>
					</tr>
				</tbody>
			<% end -%>
		</table>
	</div>

app/views/layouts/_article.html.erb
<div class="container" style="text-align: center">
	<h1><%= @article.title%>&nbsp;&nbsp;
		<% unless @article.favorites.find_by(user_id:current_user) %>
		 <%= link_to "♡",article_favorites_path(@article),method: :post %></h1>
		<% else %>
		 <%= link_to "♥",favorite_path(@article.favorites.find_by(user_id: current_user)), method: :delete %></h1>
		<% end -%>
		<p><%= @article.article%></p>
	<div class="item"><%= image_tag @article.image_url %></div><br><br>
	<div>
 		<h3>comment</h3>
		<% @comments.each do |comment| %>
			<p>
				<%= comment.comment %>
				<% if comment.user_id == current_user.id %>
				<%= link_to "delete", article_comment_path(comment.article_id, comment), method: :delete %>
				<% end -%>
			</p>
		<% end %>
		<%= form_for([@article, @comment]) do |f|%>
			<div class="field">
				<%= f.text_field :comment %>
				<%= f.hidden_field :user_id ,:value => current_user.id%>
				<%= f.submit %>
			</div>
		<% end -%>
	</div>
</div>

app/views/layouts/_favorite.html.erb
<h1><%= @user.username %>のお気に入り</h1><br><br>
<div class="container">
	<table class="table-hover">
		<thead>
			<tr>
				<th>記事名</th>
				<th>写真</th>
				<th>お気に入り数</th>
				<th>お気に入り</th>
			</tr>
		</thead>
		<% @articles.each do |f| %>	
		<tbody>
			<tr>
				<td><%= link_to f.title , article_path(f) %></td>
				<td><%= image_tag(f.image_url(:thumb).to_s) %></td>
				<td><%= f.favorites.size%></td>
				<% if current_user.favorites.find_by(article_id: f) %>
				<td><h4><%= link_to "♥",favorite_path(current_user.favorites.find_by(article_id: f)), method: :delete %></h4></td>
				<% else %>
				<td><h4><%= link_to "♡",article_favorites_path(f),method: :post %></h4></td>
				<% end -%>
			</tr>
			<% end -%>
		</tbody>
	</table>
</div>

app/views/layouts/_follow.html.erb
<h1><%= @user.username %>がフォローしている人</h1>
<br><br>
<div class="container">
	<table class="table-hover">
		<thead>
			<tr>
				<th>プロフィール</th>
				<th>名前</th>
				<th>フォロー数</th>
				<th>フォロワー数</th>
				<th>記事数</th>
				<th>フォロー</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |f| %>
			<tr>
				<td><%= image_tag f.user_image %></td>
				<td><%= link_to f.username ,user_path(f) %></td>

				<td><%= f.follows.size %></td>
				<td><%= f.reverse_follows.size %></td>
				<td><%= f.articles.size %></td>
				<% if current_user.follows.find_by(followed_id: f) %>
				<td><button class="btn btn-danger"><%= link_to "unfollow", follow_path(current_user.follows.find_by(followed_id: f)) ,method: :delete %></button></td>
				<% else %>
				<td>
					<button class="btn btn-primary"><%= link_to "follow", user_follows_path(f) , method: :post %></button></td>	
					<% end %>
				</tr>
				<% end -%>
			</tbody>
		</table>
	</div>

app/views/layouts/_footer.html.erb
<br><br><br><br><br><br><br><br>

app/views/layouts/_header.html.erb
<title>Blogapp</title>
<%= stylesheet_link_tag   "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta content="width=device-width, initial-scale=1" name="viewport">

app/views/layouts/_login.html.erb
<div class="row">
	<div class="col-md-2"><%= link_to "新規登録", new_user_registration_path %></div>
	<div class="col-md-2" ><%= link_to "ログイン", new_user_session_path %></div>
	<div class="col-md-2"><%= link_to "facebookログイン", omniauth_authorize_path(resource_name, resource_class.omniauth_providers[0]) %><br /></div>
	<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
	<div class="col-md-2"><%= link_to "Forgot your password?", new_password_path(resource_name) %></div>
	<% end -%>
</div>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/layouts/_profile.html.erb
<%= stylesheet_link_tag 'profile' %>
<h1><%= @user.username %>のページ</h1><br>
	<div class="container">
		<span>
			<%= link_to @user.follows.size, user_follows_path(@user) %> follows
		</span>
		<span>
			<%= link_to @user.reverse_follows.size,follower_user_follows_path(@user) %> followers
		</span>
		<span>
			<%= link_to @user.username+"のお気に入り",user_favorites_path(@user) %>
		</span>
			<% unless @user == current_user %> 
				<% if current_user.follows.find_by(followed_id: @user.id) %>
					<button class="btn btn-danger"><%= link_to "unfollow", follow_path(current_user.follows.find_by(followed_id: @user.id)) ,method: :delete %></button>
				<% else %>
					<button class="btn btn-primary"><%= link_to "follow", user_follows_path(@user) , method: :post %></button>
				<% end %>
			<% end -%><br><br>
		<table class="table-hover">
			<thead>
				<tr>
					<th>記事名</th>
					<th>写真</th>
					<th>作成時</th>
					<th>お気に入り数</th>
					<th></th>
				</tr>
			</thead>
		  <% @user_articles.each do |article| %>	
				<tbody>
					<tr>
						<td><%= link_to article.title, article_path(article) %></td>
						<td><%= image_tag(article.image_url(:thumb).to_s) %></td>
						<td><%= tokyotime(article.created_at) %></td>
						<td><%= article.favorites.count%></td>
						<% if article.user_id == current_user.id %>
							<td><%= link_to image_tag("/assets/drop.jpg/", :size => "30x30"), article_path(article), method: :delete , data: {confirm: "本当に削除しますか？"} -%></td>
							<% else %>
							<td></td>
						<% end -%>
					</tr>
				</tbody>
			<% end -%>
		</table>
	</div>

app/views/layouts/admin.html.erb
<%= stylesheet_link_tag   "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta content="width=device-width, initial-scale=1" name="viewport">
<%=yield %>